/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'clearSession' : IDL.Func([IDL.Text], [], []),
  'getAllSessionIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getTimetable' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'saveMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Int], [], []),
  'saveTimetable' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'clearSession' : IDL.Func([IDL.Text], [], []),
    'getAllSessionIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getTimetable' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'saveMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Int], [], []),
    'saveTimetable' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };